<?php
/**
 * Validates lib/xmr_crypto.php against authoritative Monero vectors generated by
 * the monero-python oracle (tools/xmr_vectors.json). Run on real PHP 8.3 +
 * ext-sodium (CI). Exit 1 on any mismatch. Usage: php tools/xmr-crypto-test.php
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit("cli only\n");
}
require __DIR__ . '/../lib/monero.php';      // xmr_str_add (bignum add)
require __DIR__ . '/../lib/xmr_crypto.php';

$fail = 0;
function chk(bool $cond, string $msg): void
{
    global $fail;
    echo ($cond ? "ok   " : "FAIL ") . $msg . "\n";
    if (!$cond) { $fail++; }
}
function ub(string $h): string { return hex2bin($h); }

if (!xmr_crypto_available()) {
    fwrite(STDERR, "SKIP: ext-sodium ed25519 arithmetic not available on this runtime\n");
    exit(0);
}

$vec = json_decode(file_get_contents(__DIR__ . '/xmr_vectors.json'), true);
if (!is_array($vec)) {
    fwrite(STDERR, "cannot read xmr_vectors.json\n");
    exit(1);
}

// ---- Keccak-256 ----
foreach ($vec['keccak256'] as $t) {
    chk(bin2hex(xmr_keccak256(ub($t['in']))) === $t['out'], 'keccak256(' . ($t['in'] !== '' ? substr($t['in'], 0, 16) : '(empty)') . ')');
}

// ---- Monero base58 decode (round-trip vs oracle encode) ----
foreach ($vec['base58'] as $t) {
    $d = xmr_b58_decode($t['b58']);
    chk($d !== null && bin2hex($d) === $t['hex'], 'b58 decode ' . substr($t['b58'], 0, 14));
}

// ---- address parse ----
foreach ($vec['address'] as $t) {
    $a = xmr_address_parse($t['address']);
    chk(
        $a !== null && bin2hex($a['spend']) === $t['spend_pub']
        && bin2hex($a['view']) === $t['view_pub'] && $a['net'] === $t['net'],
        'address ' . substr($t['address'], 0, 12) . '… (' . $t['net'] . ')'
    );
}
// address checksum must reject a corrupted address
$bad = $vec['address'][0]['address'];
$bad[10] = ($bad[10] === 'A') ? 'B' : 'A';
chk(xmr_address_parse($bad) === null, 'address rejects bad checksum');

// ---- ed25519 primitives (same sodium calls the scan uses) ----
$ed = $vec['ed25519'];
chk(XMR_H_HEX === $ed['H'], 'H generator constant');
chk(bin2hex(sodium_crypto_core_ed25519_scalar_add(ub($ed['scalar_add']['a']), ub($ed['scalar_add']['b']))) === $ed['scalar_add']['out'], 'scalar_add');
chk(bin2hex(sodium_crypto_core_ed25519_scalar_reduce(ub($ed['scalar_reduce']['in']) . str_repeat("\x00", 32))) === $ed['scalar_reduce']['out'], 'scalar_reduce');
chk(bin2hex(sodium_crypto_scalarmult_ed25519_base_noclamp(ub($ed['scalarmult_B']['n']))) === $ed['scalarmult_B']['out'], 'scalarmult_B');
chk(bin2hex(sodium_crypto_scalarmult_ed25519_noclamp(ub($ed['scalarmult']['n']), ub($ed['scalarmult']['p']))) === $ed['scalarmult']['out'], 'scalarmult');
chk(bin2hex(sodium_crypto_scalarmult_ed25519_noclamp(ub($ed['scalarmult_H']['n']), ub(XMR_H_HEX))) === $ed['scalarmult_H']['out'], 'scalarmult_H');

// ---- full view-key output scan (decode-outputs) ----
foreach ($vec['scan'] as $si => $s) {
    $pubkeys = [ub($s['tx_pubkey'])];
    $svk     = ub($s['svk']);
    $spend   = ub($s['spend_pub']);
    $outputs = [];
    foreach ($s['outputs'] as $o) {
        $outputs[(int) $o['idx']] = [
            'stealth'    => ub($o['stealth']),
            'view_tag'   => ub($o['view_tag']),
            'encamount'  => ub($o['encamount']),
            'commitment' => ub($o['commitment']),
        ];
    }
    ksort($outputs);
    $r = xmr_scan_tx($pubkeys, $svk, $spend, array_values($outputs));
    $byIdx = [];
    foreach ($r['owned'] as $ow) { $byIdx[$ow['index']] = $ow; }
    foreach ($s['outputs'] as $o) {
        $idx = (int) $o['idx'];
        if ($o['expect_owned']) {
            $g = $byIdx[$idx] ?? null;
            chk($g !== null && $g['amount'] === (string) $o['expect_amount'] && $g['commit_ok'] === true,
                "scan[$si] owns idx $idx = {$o['expect_amount']} (commitment verified)");
        } else {
            chk(!isset($byIdx[$idx]), "scan[$si] rejects decoy idx $idx");
        }
    }
}

echo "\n" . ($fail ? "$fail FAILURE(S)\n" : "ALL XMR CRYPTO VECTORS PASS\n");
exit($fail ? 1 : 0);
